import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const garamond = localFont({
  variable: "--font-garamond",
  display: "swap",
  src: [
    { path: "./assets/fonts/AGaramondPro-Regular.otf", weight: "400", style: "normal" },
    { path: "./assets/fonts/AGaramondPro-Italic.otf", weight: "400", style: "italic" },
    { path: "./assets/fonts/AGaramondPro-Bold.otf", weight: "700", style: "normal" },
    { path: "./assets/fonts/AGaramondPro-BoldItalic.otf", weight: "700", style: "italic" },
  ],
});

const seasons = localFont({
  variable: "--font-seasons",
  display: "swap",
  src: [{ path: "./assets/fonts/TheSeasonsRegular.ttf", weight: "400", style: "normal" }],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${garamond.variable} ${seasons.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
